spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kakaopay?useUnicode=true&characterEncoding=utf-8
    # url: jdbc:mariadb://kakaopay_db_1:3306/kakaopay?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_data.sql
      schema-locations: classpath:sql/barcodes.sql,classpath:sql/business_type.sql,classpath:sql/member_point_information.sql,classpath:sql/members.sql,classpath:sql/merchants.sql,classpath:sql/point_transaction_histories.sql
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
